import { Link } from 'react-router-dom'
import Seo from '../components/Seo.jsx'
import { absoluteUrl, SITE } from '../config/site.js'
import { getGuide, GUIDES, GUIDE_UPDATED_DATE } from '../data/guides.js'
import '../styles/guides.css'

function WithoutMentor() {
  return <>
    <section id="choose" aria-labelledby="choose-title"><h2 id="choose-title">1. Choose a question you can actually examine.</h2><p>Replace a large topic with one comparison, pattern, passage, or mathematical case. Name the evidence you will use before promising a result. “How does climate change affect cities?” is a topic. “Do two nearby public weather stations show the same pattern of hot days over the same recorded years?” is a question you can inspect.</p><p>Choose an initial task that fits your current skills. A careful replication of one published calculation can teach more than a claim of a new discovery you cannot check.</p></section>
    <section id="evidence" aria-labelledby="evidence-title"><h2 id="evidence-title">2. Check the evidence before choosing the method.</h2><p>Read a short overview, then follow a reference to an original paper or dataset. Record its author or organization, title, date, URL, and what it measures. With public data, check the units, missing values, collection period, and permission to reuse it. Public availability does not automatically make two datasets comparable.</p><ul><li><strong>Mathematics:</strong> test a small case, identify the assumptions, and work through a proof step.</li><li><strong>Humanities:</strong> choose a defined set of passages and explain the rule you use to compare them.</li><li><strong>Data analysis:</strong> make one plot or summary of a documented public dataset, preserving the original file.</li></ul><p>Ask a teacher before a project involving people, animals, sensitive personal information, hazardous materials, or equipment you are not trained to use. Some investigations need formal supervision and approval.</p></section>
    <section id="attempt" aria-labelledby="attempt-title"><h2 id="attempt-title">3. Make one small attempt and keep the record.</h2><p>Write the question, evidence, and planned comparison first. Then try one calculation, close reading, or plot. Save the steps, including changes, failed attempts, and results that disagree with your expectation. Treat an observation as a starting point for explanation; it does not establish a cause by itself.</p><div className="guide-worked-example"><p className="eyebrow">WORKED EXAMPLE · constructed teaching material</p><h3>Two weather stations, one comparison.</h3><dl><div><dt>Question</dt><dd>Do two nearby stations report the same number of days above a chosen temperature during the same summer?</dd></div><div><dt>First check</dt><dd>Check that both use the same temperature unit and daily measurement, and identify dates missing from either record.</dd></div><div><dt>First attempt</dt><dd>Use dates available at both stations, report the threshold, and count the days for each station.</dd></div><div><dt>Limitation</dt><dd>A difference could reflect station placement or measurement coverage. This comparison alone cannot establish a climate trend.</dd></div></dl><p>No observations or numerical results are claimed in this example.</p></div></section>
    <section id="feedback" aria-labelledby="feedback-title"><h2 id="feedback-title">4. Ask for a specific piece of feedback.</h2><p>A teacher can help you find a useful next step even when they are not a specialist in the topic. Share a brief note with your question, one source, what you tried, your result, and where you are stuck. Ask something answerable, such as “Is this comparison fair?” or “Which assumption should I check next?”</p><p>If you later contact a researcher, read their work first and explain the connection. Their time and response are not guaranteed. A mentored program may be a better fit when you need specialist equipment or sustained supervision.</p></section>
    <section aria-labelledby="mentor-questions"><h2 id="mentor-questions">Common questions</h2><h3>Does independent research have to be original immediately?</h3><p>No. Start by understanding and checking an existing result. A possible extension needs a literature check and qualified feedback before you describe it as original.</p><h3>Can artificial intelligence choose the project for me?</h3><p>It can suggest search terms or explain terminology. Check sources, calculations, and citations yourself. A fluent response is not evidence that a claim is true or that an investigation is feasible.</p><h3>When should I look for a mentor?</h3><p>Seek guidance when a question exceeds your methods, when you cannot evaluate a crucial assumption, or when the investigation requires supervision. You can bring your documented first attempt to that conversation.</p></section>
  </>
}

function FirstPaper() {
  return <>
    <section id="choose" aria-labelledby="choose-title"><h2 id="choose-title">1. Find an accessible paper tied to your question.</h2><p>Use a review or introductory source to learn the terms, then follow a reference to an original study. In Google Scholar, search a known paper title in quotation marks. Check the publisher page, full-text links, or “All versions” for a version you can read. Record whether you are reading a preprint or the published version.</p><p>Choose one reason to read: understanding a method, checking a claim, or seeing how a question was investigated. The reading strategy below is an introductory exercise; different disciplines and paper formats need different approaches.</p></section>
    <section id="claim" aria-labelledby="claim-title"><h2 id="claim-title">2. Make a first pass for the question and claim.</h2><p>Read the title, abstract, introduction, and conclusion. In your own words, write the question and the authors’ main claim. Mark important unfamiliar terms without trying to solve every detail yet. Separate what the paper reports from what the authors suggest might follow.</p><p>For a theoretical paper, identify the statement, assumptions, and definitions. For a humanities paper, identify the interpretation and the primary material it uses. An experimental paper may instead identify a population, intervention, comparison, and outcome.</p></section>
    <section id="trace" aria-labelledby="trace-title"><h2 id="trace-title">3. Trace one result back to its evidence.</h2><p>Choose one figure, table, argument, or theorem. Read its caption or statement before the surrounding discussion. Ask what was compared, what the axes or terms mean, and which conditions are required. Then look at the method or proof that connects the evidence to the claim.</p><p>For a plot, check units, sample size, missing data, uncertainty, and whether an axis changes scale. For a proof, work through a small example and locate the assumptions used in each step. If you cannot follow a step, record the exact point rather than filling the gap with a guess.</p><div className="guide-worked-example"><p className="eyebrow">WORKED EXAMPLE · constructed teaching material</p><h3>A claim and a missing comparison.</h3><p>Suppose a paper reports lower average temperatures at shaded locations. Before writing “shade caused the difference,” inspect whether the locations were measured at comparable times, on comparable surfaces, and under similar conditions. If these details are absent, your note should say the reported association leaves other explanations open.</p><p>This example describes a reading exercise, not a real study or verified finding.</p></div></section>
    <section id="record" aria-labelledby="record-title"><h2 id="record-title">4. Make a note you can check later.</h2><p>Keep direct quotations clearly marked and include their page, section, or figure location. Keep your interpretation in separate wording. A reference manager can help organize the source, attachment, and notes; check the imported title, authors, year, and DOI.</p><div className="guide-table-wrap"><table><caption>A six-part note for one paper</caption><thead><tr><th scope="col">Field</th><th scope="col">What to write</th></tr></thead><tbody><tr><th scope="row">Source</th><td>Title, authors, year, version, and DOI or URL.</td></tr><tr><th scope="row">Question</th><td>The problem the paper actually investigates.</td></tr><tr><th scope="row">Claim</th><td>One result in your own words.</td></tr><tr><th scope="row">Evidence</th><td>The specific figure, table, passage, method, or proof.</td></tr><tr><th scope="row">Limitation</th><td>A condition or uncertainty that affects the interpretation.</td></tr><tr><th scope="row">Next step</th><td>One term to learn, result to check, or reference to follow.</td></tr></tbody></table></div><p>Follow a reference for background, or use “Cited by” to find later papers. A citation count is not a substitute for evaluating the argument.</p></section>
    <section aria-labelledby="paper-questions"><h2 id="paper-questions">Common questions</h2><h3>Do I have to understand every equation?</h3><p>No. Your first goal can be to identify the question, claim, and evidence. Before using a method in your own project, work through the steps and assumptions it needs.</p><h3>Can I rely on the abstract or an AI summary?</h3><p>An abstract or summary can orient you. Check the original result and its conditions before citing it. If you use AI to explain a passage, compare the explanation with the passage and ask a teacher about unresolved gaps.</p><h3>What if the paper is too difficult?</h3><p>Read a background source, choose a smaller result, or switch to a more accessible paper. Write down which prerequisite is missing so your next reading addresses it.</p></section>
  </>
}

export default function ResearchGuidePage({ path }) {
  const guide = getGuide(path)
  const otherGuide = GUIDES.find(item => item.path !== path)
  const schema = [
    { '@context': 'https://schema.org', '@type': ['Article', 'LearningResource'], '@id': `${absoluteUrl(path)}#guide`, url: absoluteUrl(path), headline: guide.heading, name: guide.heading, description: guide.description, abstract: guide.answer, dateModified: GUIDE_UPDATED_DATE, inLanguage: 'en', learningResourceType: 'Guide', educationalLevel: 'High school', isAccessibleForFree: true, publisher: { '@type': 'Organization', name: SITE.name, url: absoluteUrl('/') }, citation: guide.sources.map(source => ({ '@type': 'CreativeWork', name: source.title, url: source.url })) },
    { '@context': 'https://schema.org', '@type': 'BreadcrumbList', itemListElement: [{ '@type': 'ListItem', position: 1, name: SITE.name, item: absoluteUrl('/') }, { '@type': 'ListItem', position: 2, name: 'Start on your own', item: absoluteUrl('/start-here') }, { '@type': 'ListItem', position: 3, name: guide.heading, item: absoluteUrl(path) }] },
  ]
  return <><Seo title={guide.title} description={guide.description} pathname={path} type="article" jsonLd={schema} /><main id="main-content" className="research-guide"><article>
    <nav className="guide-breadcrumbs" aria-label="Breadcrumb"><Link to="/start-here">Start on your own</Link><span aria-hidden="true"> / </span><span>Research guide</span></nav>
    <header className="guide-heading"><p className="eyebrow">A practical student guide</p><h1>{guide.heading}</h1><p className="guide-answer">{guide.answer}</p><p className="guide-updated">Research Starter Lab · Updated <time dateTime={GUIDE_UPDATED_DATE}>October 7, 2026</time></p></header>
    <nav className="guide-jumps" aria-label="On this page"><a href="#choose">Choose a starting point</a><a href={path === GUIDES[0].path ? '#evidence' : '#claim'}>Check the evidence</a><a href={path === GUIDES[0].path ? '#feedback' : '#record'}>Your next step</a></nav>
    {path === GUIDES[0].path ? <WithoutMentor /> : <FirstPaper />}
    <section className="guide-sources" aria-labelledby="sources-title"><h2 id="sources-title">Sources and further reading</h2><p>The steps and constructed examples are this site’s introductory teaching material. These sources support finding papers, reading research, and organizing evidence. This guide does not certify a project’s novelty, safety, or publishability.</p><ul>{guide.sources.map(source => <li key={source.url}><a href={source.url} target="_blank" rel="noopener noreferrer">{source.title}<span aria-hidden="true"> ↗</span><span className="sr-only"> (opens in a new tab)</span></a></li>)}</ul></section>
    <nav className="guide-next" aria-label="Continue researching"><Link to={otherGuide.path}>{otherGuide.heading} →</Link><Link to="/resources">Find papers, data, and programs →</Link><Link to="/my-research">Keep my research progress →</Link></nav>
  </article></main></>
}
